In [1]:
import pandas as pd
from scipy.io import loadmat
import numpy as np
import matplotlib.pyplot as plt

In [2]:
mat_data = loadmat('data 1\\degradation_data.mat')

data_dict = {}

for key in mat_data:
    if not key.startswith('__'):
        value = mat_data[key]
        if isinstance(value, (list, tuple)):
            try:
                arr = np.array(value)
                if arr.ndim == 1:
                    data_dict[key] = arr
            except:
                continue
        if isinstance(value, (int, float, complex)):
            data_dict[key] = [value]
        elif isinstance(value, np.ndarray):
            # Se è un vettore 1D, lo includiamo direttamente
            if value.ndim == 1:
                data_dict[key] = value
            # Se è 2D con una sola colonna o riga, lo convertiamo
            elif value.ndim == 2:
                if value.shape[0] == 1 or value.shape[1] == 1:
                    data_dict[key] = value.flatten()
            # Altrimenti lo saltiamo per evitare ambiguità
            else:
                pass

# Creiamo il DataFrame. Useremo la lunghezza minima comune per evitare errori di forma.
min_len = min(len(col) for col in data_dict.values())
trimmed_data = {k: v[:min_len] for k, v in data_dict.items()}
df = pd.DataFrame(trimmed_data)

df.head()

,Q_first,V_first,Q_last,V_last,throughput_capacities,discharge_capacities,SOH_values,loss_lithium_ah,Q_SEI,Q_SEI_cr,Q_plating,Q_LLI,Qt,charge_times,discharges_times,rest_times,hold_times,total_times,Voltage
0,0.000000,3.988174,0.058375,3.958747,4.822059,4.822059,1.000000,0.014204,0.000052,0.001437,0.012493,0.014204,9.629674,1.616504,0.964412,4.137878,1.616504,8.335298,"[[3.9881736765921536, 3.9297893740949164, 3.89..."
1,0.083333,3.929789,0.141709,3.904890,14.435716,4.820486,0.999674,0.015800,0.000111,0.002034,0.013097,0.015800,19.242004,1.612746,0.961208,4.140315,1.612746,8.327016,"[[3.972006527133013, 3.9194295017981244, 3.885..."
2,0.166667,3.895303,0.225042,3.864899,24.046785,4.818979,0.999361,0.017251,0.000170,0.002492,0.013711,0.017251,28.851755,1.612050,0.960956,4.143591,1.612050,8.328647,"[[3.9721232020519275, 3.9194676412426377, 3.88..."
3,0.250000,3.873345,0.308375,3.839235,33.655346,4.817599,0.999075,0.018623,0.000227,0.002878,0.014323,0.018623,38.459105,1.611421,0.960718,4.146721,1.611421,8.330281,"[[3.9722116973130213, 3.9194906341394065, 3.88..."
4,0.333333,3.860796,0.391709,3.824565,43.261560,4.816295,0.998805,0.019942,0.000285,0.003219,0.014931,0.019942,48.064176,1.610823,0.960491,4.149782,1.610823,8.331919,"[[3.9722890926598313, 3.9195250584638313, 3.88..."

In [3]:
df.to_csv('data 1\\degradation.csv', index=False)

In [4]:
mat_data = loadmat('data 1\\selected_impedance_cycles.mat')

data_dict = {}

for key in mat_data:
    if not key.startswith('__'):
        value = mat_data[key]
        if isinstance(value, (list, tuple)):
            try:
                arr = np.array(value)
                if arr.ndim == 1:
                    data_dict[key] = arr
            except:
                continue
        if isinstance(value, (int, float, complex)):
            data_dict[key] = [value]
        elif isinstance(value, np.ndarray):
            # Se è un vettore 1D, lo includiamo direttamente
            if value.ndim == 1:
                data_dict[key] = value
            # Se è 2D con una sola colonna o riga, lo convertiamo
            elif value.ndim == 2:
                if value.shape[0] == 1 or value.shape[1] == 1:
                    data_dict[key] = value.flatten()
            # Altrimenti lo saltiamo per evitare ambiguità
            else:
                pass

# Creiamo il DataFrame. Useremo la lunghezza minima comune per evitare errori di forma.
min_len = min(len(col) for col in data_dict.values())
trimmed_data = {k: v[:min_len] for k, v in data_dict.items()}
df = pd.DataFrame(trimmed_data)

df.head()

,Z_real_cycle_1,Z_real_cycle_100,Z_real_cycle_300,Z_real_cycle_400,Z_real_cycle_500,Z_real_cycle_700,Z_real_cycle_900,Z_real_cycle_1000
0,0.141697,0.135363,0.136406,0.143900,0.142079,0.140363,0.143196,0.145212
1,0.134993,0.131730,0.132078,0.134729,0.134730,0.135482,0.137924,0.139406
2,0.129839,0.128011,0.128343,0.129082,0.129885,0.131771,0.134183,0.135485
3,0.126656,0.125429,0.125826,0.125840,0.126990,0.129335,0.131760,0.132998
4,0.124729,0.123628,0.123958,0.123720,0.124936,0.127338,0.129679,0.130852

In [5]:
df.to_csv('data 1\\impedences.csv', index=False)